import { randomUUID } from 'node:crypto'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { config, IMAGE_EXTENSIONS, IMAGE_MIME_TYPES } from '@/lib/config'

/** Only names generated by savePhoto() may ever be read back from disk. */
const SAFE_PHOTO_NAME = /^[A-Za-z0-9_-]+\.(?:jpg|jpeg|png|webp)$/

/** The only image formats the uploader keeps. */
type SupportedFormat = 'jpeg' | 'png' | 'webp'

const FORMAT_TO_MIME: Record<SupportedFormat, string> = {
  jpeg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
}

function asSupportedFormat(value: string | undefined): SupportedFormat | null {
  return value === 'jpeg' || value === 'png' || value === 'webp' ? value : null
}

export class UploadError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'UploadError'
  }
}

export function isSafePhotoName(name: string): boolean {
  return SAFE_PHOTO_NAME.test(name)
}

/** Absolute path for a stored photo, guarded against path traversal. */
export function photoPath(name: string): string {
  if (!isSafePhotoName(name)) {
    throw new UploadError(`Refusing to access unsafe photo name "${name}"`)
  }
  return path.join(config.uploads.dir, name)
}

export async function ensureUploadDir(): Promise<void> {
  await mkdir(config.uploads.dir, { recursive: true })
}

/** MIME and size checks shared by every upload path. */
export function assertPhotoFile(file: File): void {
  if (!IMAGE_MIME_TYPES.includes(file.type as (typeof IMAGE_MIME_TYPES)[number])) {
    throw new UploadError(
      `Unsupported image type "${file.type || 'unknown'}". Use JPEG, PNG or WebP.`,
    )
  }
  if (file.size <= 0) {
    throw new UploadError('The uploaded photo is empty.')
  }
  if (file.size > config.uploads.maxBytes) {
    const limit = Math.round(config.uploads.maxBytes / (1024 * 1024))
    throw new UploadError(`The photo is larger than ${limit} MB.`)
  }
}

/**
 * Decodes and normalises an image entirely in memory — EXIF rotation applied,
 * size capped, re-encoded in its own format — and writes nothing. Read-only
 * callers (the photo search) use this; storing callers use savePhotoBuffer().
 *
 * The real format is detected with sharp, so a wrong Content-Type cannot smuggle
 * a non-image in.
 */
export async function preparePhotoBuffer(
  buffer: Buffer,
): Promise<{ buffer: Buffer; extension: string }> {
  let format: SupportedFormat
  let width: number | undefined
  let height: number | undefined

  try {
    const metadata = await sharp(buffer).metadata()
    const detected = asSupportedFormat(metadata.format)
    if (!detected) {
      throw new UploadError(`Unsupported image format "${metadata.format ?? 'unknown'}".`)
    }
    format = detected
    width = metadata.width
    height = metadata.height
  } catch (error) {
    if (error instanceof UploadError) throw error
    throw new UploadError('The uploaded file is not a readable image.')
  }

  const extension = IMAGE_EXTENSIONS[FORMAT_TO_MIME[format]] ?? '.jpg'

  let pipeline = sharp(buffer).rotate()
  if (
    (width ?? 0) > config.uploads.maxDimension ||
    (height ?? 0) > config.uploads.maxDimension
  ) {
    pipeline = pipeline.resize({
      width: config.uploads.maxDimension,
      height: config.uploads.maxDimension,
      fit: 'inside',
      withoutEnlargement: true,
    })
  }

  return { buffer: await pipeline.toFormat(format).toBuffer(), extension }
}

/**
 * Validates, normalises (EXIF rotation, size cap) and stores an uploaded photo.
 * Returns the generated file name to persist on the Item row.
 */
export async function savePhoto(file: File): Promise<string> {
  assertPhotoFile(file)
  return savePhotoBuffer(Buffer.from(await file.arrayBuffer()))
}

/** Same as savePhoto() but for bytes we already hold. */
export async function savePhotoBuffer(buffer: Buffer): Promise<string> {
  const prepared = await preparePhotoBuffer(buffer)
  const name = `${randomUUID()}${prepared.extension}`

  await ensureUploadDir()
  await writeFile(photoPath(name), prepared.buffer)
  return name
}

export async function readPhoto(name: string): Promise<Buffer> {
  return readFile(photoPath(name))
}

export async function deletePhoto(name: string): Promise<void> {
  try {
    await unlink(photoPath(name))
  } catch {
    // A missing file must never break an API call.
  }
}

/** Downscaled copy used by list views and thumbnails. */
export async function renderPhotoVariant(name: string, width: number): Promise<Buffer> {
  return sharp(photoPath(name))
    .resize({ width, withoutEnlargement: true })
    .toBuffer()
}

export function photoContentType(name: string): string {
  const extension = path.extname(name).toLowerCase()
  switch (extension) {
    case '.png':
      return 'image/png'
    case '.webp':
      return 'image/webp'
    default:
      return 'image/jpeg'
  }
}
